import { supabase } from "../../koneksi_supabase";

/**
 * Public interface for Laporan Muslimun data (used in application logic)
 */
export interface LapMuslimunData {
  id?: number; // Optional since Supabase auto-generates primary key
  nama_kelompok: string;
  bulan: string;
  tahun: string;
  isi_laporan: string;
}

/**
 * Database response interface (matches exact Supabase table structure)
 */
interface DatabaseLapMuslimunData {
  id: number;
  nama_kelompok: string;
  bulan: string;
  tahun: string;
  isi_laporan: string;
}

/**
 * Transform database response to public LapMuslimunData interface
 * @param dbData - Raw data from Supabase
 * @returns Transformed LapMuslimunData array
 */
function transformDatabaseResponse(dbData: DatabaseLapMuslimunData[]): LapMuslimunData[] {
  return dbData.map(item => ({
    id: item.id,
    nama_kelompok: item.nama_kelompok,
    bulan: item.bulan,
    tahun: item.tahun,
    isi_laporan: item.isi_laporan,
  }));
}

/**
 * Validate Laporan Muslimun data input before saving to database
 * @param data - LapMuslimunData to validate
 * @returns Boolean indicating validation status
 * @throws Error if validation fails
 */
function validateLapMuslimunData(data: Omit<LapMuslimunData, 'id'>): boolean {
  const requiredFields = ['nama_kelompok', 'bulan', 'tahun', 'isi_laporan'];
  const missingFields = requiredFields.filter(field => !(field in data) || !data[field as keyof Omit<LapMuslimunData, 'id'>]);

  if (missingFields.length > 0) {
    throw new Error(`Missing required fields: ${missingFields.join(', ')}`);
  }

  return true;
}

/**
 * Create new Laporan Muslimun data entry
 * @param data - LapMuslimunData without id (auto-generated by Supabase)
 * @returns Promise<LapMuslimunData> - Created Laporan Muslimun data with id
 */
export async function createLapMuslimunData(data: Omit<LapMuslimunData, 'id'>): Promise<LapMuslimunData> {
  try {
    validateLapMuslimunData(data);
    
    const { data: insertedData, error } = await supabase
      .from('laporan_muslimun')
      .insert([data])
      .select()
      .single();

    if (error) {
      console.error('Error creating Laporan Muslimun data:', error);
      throw new Error(`Failed to create Laporan Muslimun data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([insertedData]);
    return transformed[0];
  } catch (error) {
    console.error('Error in createLapMuslimunData:', error);
    throw error;
  }
}

/**
 * Fetch all Laporan Muslimun data entries
 * @returns Promise<LapMuslimunData[]> - Array of all Laporan Muslimun data
 */
export async function getAllLapMuslimunData(): Promise<LapMuslimunData[]> {
  try {
    const { data, error } = await supabase
      .from('laporan_muslimun')
      .select('*')
      .order('nama_kelompok', { ascending: true });

    if (error) {
      console.error('Error fetching all Laporan Muslimun data:', error);
      throw new Error(`Failed to fetch Laporan Muslimun data: ${error.message}`);
    }

    if (!data || data.length === 0) {
      console.warn('No Laporan Muslimun data found in database');
      return [];
    }

    return transformDatabaseResponse(data);
  } catch (error) {
    console.error('Error in getAllLapMuslimunData:', error);
    throw error;
  }
}

/**
 * Fetch Laporan Muslimun data by id
 * @param id - Laporan Muslimun data id
 * @returns Promise<LapMuslimunData | null> - Laporan Muslimun data or null if not found
 */
export async function getLapMuslimunDataById(id: number): Promise<LapMuslimunData | null> {
  try {
    const { data, error } = await supabase
      .from('laporan_muslimun')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        console.warn(`No Laporan Muslimun data found with id: ${id}`);
        return null;
      }
      console.error('Error fetching Laporan Muslimun data by id:', error);
      throw new Error(`Failed to fetch Laporan Muslimun data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([data]);
    return transformed[0];
  } catch (error) {
    console.error('Error in getLapMuslimunDataById:', error);
    throw error;
  }
}

/**
 * Update existing Laporan Muslimun data entry
 * @param id - Laporan Muslimun data id to update
 * @param data - Partial LapMuslimunData with fields to update
 * @returns Promise<LapMuslimunData> - Updated Laporan Muslimun data
 */
export async function updateLapMuslimunData(id: number, data: Partial<Omit<LapMuslimunData, 'id'>>): Promise<LapMuslimunData> {
  try {
    if (Object.keys(data).length === 0) {
      throw new Error('No fields provided for update');
    }

    const { data: updatedData, error } = await supabase
      .from('laporan_muslimun')
      .update(data)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        throw new Error(`No Laporan Muslimun data found with id: ${id}`);
      }
      console.error('Error updating Laporan Muslimun data:', error);
      throw new Error(`Failed to update Laporan Muslimun data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([updatedData]);
    return transformed[0];
  } catch (error) {
    console.error('Error in updateLapMuslimunData:', error);
    throw error;
  }
}

/**
 * Delete Laporan Muslimun data entry by id
 * @param id - Laporan Muslimun data id to delete
 * @returns Promise<boolean> - True if deletion successful
 */
export async function deleteLapMuslimunData(id: number): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('laporan_muslimun')
      .delete()
      .eq('id', id);

    if (error) {
      if (error.code === 'PGRST116') {
        throw new Error(`No Laporan Muslimun data found with id: ${id}`);
      }
      console.error('Error deleting Laporan Muslimun data:', error);
      throw new Error(`Failed to delete Laporan Muslimun data: ${error.message}`);
    }

    return true;
  } catch (error) {
    console.error('Error in deleteLapMuslimunData:', error);
    throw error;
  }
}

/**
 * Filter Laporan Muslimun data by specific criteria
 * @param filters - Partial LapMuslimunData with filter values
 * @param page - Page number for pagination (default: 1)
 * @param limit - Number of items per page (default: 10)
 * @returns Promise<LapMuslimunData[]> - Filtered Laporan Muslimun data with pagination
 */
export async function filterLapMuslimunData(
  filters: Partial<Omit<LapMuslimunData, 'id'>>,
  page: number = 1,
  limit: number = 10
): Promise<LapMuslimunData[]> {
  try {
    if (Object.keys(filters).length === 0) {
      throw new Error('No filter criteria provided');
    }

    let query = supabase.from('laporan_muslimun').select('*');

    // Build filter query
    Object.entries(filters).forEach(([key, value]) => {
      if (value) {
        query = query.ilike(key, `%${value}%`);
      }
    });

    // Add pagination
    const offset = (page - 1) * limit;
    query = query.range(offset, offset + limit - 1).order('nama_kelompok', { ascending: true });

    const { data, error } = await query;

    if (error) {
      console.error('Error filtering Laporan Muslimun data:', error);
      throw new Error(`Failed to filter Laporan Muslimun data: ${error.message}`);
    }

    if (!data || data.length === 0) {
      console.warn('No Laporan Muslimun data found matching filter criteria');
      return [];
    }

    return transformDatabaseResponse(data);
  } catch (error) {
    console.error('Error in filterLapMuslimunData:', error);
    throw error;
  }
}

// Legacy export for backward compatibility (deprecated)
// Use getAllLapMuslimunData() instead
export const lapMuslimunData: LapMuslimunData[] = [];