import { supabase } from "../../koneksi_supabase";

/**
 * Public interface for CBR data (used in application logic)
 */
export interface CbrData {
  id?: number; // Optional since Supabase auto-generates primary key
  nama_cbr: string;
  tgl_lahir_cbr: string; // Format: YYYY-MM-DD (matches Supabase date type)
  kelompok_cbr: string;
  kelas_sekolah_cbr: string;
  jenis_kelamin_cbr: string;
}

/**
 * Database response interface (matches exact Supabase table structure)
 */
interface DatabaseCbrData {
  id: number;
  nama_cbr: string;
  tgl_lahir_cbr: string;
  kelompok_cbr: string;
  kelas_sekolah_cbr: string;
  jenis_kelamin_cbr: string;
}

/**
 * Transform database response to public CbrData interface
 * @param dbData - Raw data from Supabase
 * @returns Transformed CbrData array
 */
function transformDatabaseResponse(dbData: DatabaseCbrData[]): CbrData[] {
  return dbData.map(item => ({
    id: item.id,
    nama_cbr: item.nama_cbr,
    tgl_lahir_cbr: item.tgl_lahir_cbr,
    kelompok_cbr: item.kelompok_cbr,
    kelas_sekolah_cbr: item.kelas_sekolah_cbr,
    jenis_kelamin_cbr: item.jenis_kelamin_cbr
  }));
}

/**
 * Validate CBR data input before saving to database
 * @param data - CbrData to validate
 * @returns Boolean indicating validation status
 * @throws Error if validation fails
 */
function validateCbrData(data: Omit<CbrData, 'id'>): boolean {
  const requiredFields = ['nama_cbr', 'kelompok_cbr', 'jenis_kelamin_cbr'];
  const missingFields = requiredFields.filter(field => !(field in data) || !data[field as keyof Omit<CbrData, 'id'>]);

  if (missingFields.length > 0) {
    throw new Error(`Missing required fields: ${missingFields.join(', ')}`);
  }

  // Validate date format (YYYY-MM-DD)
  const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
  if (!dateRegex.test(data.tgl_lahir_cbr)) {
    throw new Error('Invalid date format. Use YYYY-MM-DD');
  }

  // Validate jenis_kelamin_cbr
  if (!['L', 'P'].includes(data.jenis_kelamin_cbr)) {
    throw new Error('Jenis kelamin harus L (Laki-laki) atau P (Perempuan).');
  }

  return true;
}

/**
 * Create new CBR data entry
 * @param data - CbrData without id (auto-generated by Supabase)
 * @returns Promise<CbrData> - Created CBR data with id
 */
export async function createCbrData(data: Omit<CbrData, 'id'>): Promise<CbrData> {
  try {
    validateCbrData(data);
    
    const { data: insertedData, error } = await supabase
      .from('data_caberawit')
      .insert([data])
      .select()
      .single();

    if (error) {
      console.error('Error creating CBR data:', error);
      throw new Error(`Failed to create CBR data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([insertedData]);
    return transformed[0];
  } catch (error) {
    console.error('Error in createCbrData:', error);
    throw error;
  }
}

/**
 * Fetch all CBR data entries
 * @returns Promise<CbrData[]> - Array of all CBR data
 */
export async function getAllCbrData(): Promise<CbrData[]> {
  try {
    const { data, error } = await supabase
      .from('data_caberawit')
      .select('*')
      .order('nama_cbr', { ascending: true });

    if (error) {
      console.error('Error fetching all CBR data:', error);
      throw new Error(`Failed to fetch CBR data: ${error.message}`);
    }

    if (!data || data.length === 0) {
      console.warn('No CBR data found in database');
      return [];
    }

    return transformDatabaseResponse(data);
  } catch (error) {
    console.error('Error in getAllCbrData:', error);
    throw error;
  }
}

/**
 * Fetch CBR data by id
 * @param id - CBR data id
 * @returns Promise<CbrData | null> - CBR data or null if not found
 */
export async function getCbrDataById(id: number): Promise<CbrData | null> {
  try {
    const { data, error } = await supabase
      .from('data_caberawit')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        console.warn(`No CBR data found with id: ${id}`);
        return null;
      }
      console.error('Error fetching CBR data by id:', error);
      throw new Error(`Failed to fetch CBR data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([data]);
    return transformed[0];
  } catch (error) {
    console.error('Error in getCbrDataById:', error);
    throw error;
  }
}

/**
 * Update existing CBR data entry
 * @param id - CBR data id to update
 * @param data - Partial CbrData with fields to update
 * @returns Promise<CbrData> - Updated CBR data
 */
export async function updateCbrData(id: number, data: Partial<Omit<CbrData, 'id'>>): Promise<CbrData> {
  try {
    if (Object.keys(data).length === 0) {
      throw new Error('No fields provided for update');
    }

    // Validate date if provided
    if (data.tgl_lahir_cbr) {
      const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
      if (!dateRegex.test(data.tgl_lahir_cbr)) {
        throw new Error('Invalid date format. Use YYYY-MM-DD');
      }
    }

    const { data: updatedData, error } = await supabase
      .from('data_caberawit')
      .update(data)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        throw new Error(`No CBR data found with id: ${id}`);
      }
      console.error('Error updating CBR data:', error);
      throw new Error(`Failed to update CBR data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([updatedData]);
    return transformed[0];
  } catch (error) {
    console.error('Error in updateCbrData:', error);
    throw error;
  }
}

/**
 * Delete CBR data entry by id
 * @param id - CBR data id to delete
 * @returns Promise<boolean> - True if deletion successful
 */
export async function deleteCbrData(id: number): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('data_caberawit')
      .delete()
      .eq('id', id);

    if (error) {
      if (error.code === 'PGRST116') {
        throw new Error(`No CBR data found with id: ${id}`);
      }
      console.error('Error deleting CBR data:', error);
      throw new Error(`Failed to delete CBR data: ${error.message}`);
    }

    return true;
  } catch (error) {
    console.error('Error in deleteCbrData:', error);
    throw error;
  }
}

/**
 * Filter CBR data by specific criteria
 * @param filters - Partial CbrData with filter values
 * @param page - Page number for pagination (default: 1)
 * @param limit - Number of items per page (default: 10)
 * @returns Promise<CbrData[]> - Filtered CBR data with pagination
 */
export async function filterCbrData(
  filters: Partial<Omit<CbrData, 'id'> & { kelas_ngaji?: string }>,
): Promise<{ data: CbrData[]; totalCount: number }> {
  try {
    let query = supabase.from('data_caberawit').select('*', { count: 'exact' });

    // Build filter query
    Object.entries(filters).forEach(([key, value]) => {
      if (value) {
        if (key === 'kelas_ngaji') {
          let kelasSekolahValues: string[] = [];
          switch (value) {
            case "PAUD":
              kelasSekolahValues = ["Belum Sekolah", "PAUD", "TK/RA"];
              break;
            case "A":
              kelasSekolahValues = ["Kelas 1", "Kelas 2"];
              break;
            case "B":
              kelasSekolahValues = ["Kelas 3", "Kelas 4"];
              break;
            case "C":
              kelasSekolahValues = ["Kelas 5", "Kelas 6"];
              break;
            default:
              break;
          }
          if (kelasSekolahValues.length > 0) {
            query = query.in('kelas_sekolah_cbr', kelasSekolahValues);
          }
        } else {
          query = query.ilike(key, `%${value}%`);
        }
      }
    });

    const { data, error, count } = await query;

    if (error) {
      console.error('Error filtering CBR data:', error);
      throw new Error(`Failed to filter CBR data: ${error.message}`);
    }

    if (!data || data.length === 0) {
      console.warn('No CBR data found matching filter criteria');
      return { data: [], totalCount: 0 };
    }

    return { data: transformDatabaseResponse(data), totalCount: count || 0 };
  } catch (error) {
    console.error('Error in filterCbrData:', error);
    throw error;
  }
}

// Legacy export for backward compatibility (deprecated)
// Use getAllCbrData() instead
export const cbrData: CbrData[] = [];