import { supabase } from "../../koneksi_supabase";

/**
 * Public interface for Praremaja data (used in application logic)
 */
export interface PrjData {
  id?: number; // Optional since Supabase auto-generates primary key
  nama_prj: string;
  tgl_lahir_prj: string; // Format: YYYY-MM-DD (matches Supabase date type)
  kelompok_prj: string;
  kelas_sekolah_prj: string;
}

/**
 * Database response interface (matches exact Supabase table structure)
 */
interface DatabasePrjData {
  id: number;
  nama_prj: string;
  tgl_lahir_prj: string;
  kelompok_prj: string;
  kelas_sekolah_prj: string;
}

/**
 * Transform database response to public PrjData interface
 * @param dbData - Raw data from Supabase
 * @returns Transformed PrjData array
 */
function transformDatabaseResponse(dbData: DatabasePrjData[]): PrjData[] {
  return dbData.map(item => ({
    id: item.id,
    nama_prj: item.nama_prj,
    tgl_lahir_prj: item.tgl_lahir_prj,
    kelompok_prj: item.kelompok_prj,
    kelas_sekolah_prj: item.kelas_sekolah_prj
  }));
}

/**
 * Validate Praremaja data input before saving to database
 * @param data - PrjData to validate
 * @returns Boolean indicating validation status
 * @throws Error if validation fails
 */
function validatePrjData(data: Omit<PrjData, 'id'>): boolean {
  const requiredFields = ['nama_prj', 'tgl_lahir_prj', 'kelompok_prj', 'kelas_sekolah_prj'];
  const missingFields = requiredFields.filter(field => !(field in data) || !data[field as keyof Omit<PrjData, 'id'>]);

  if (missingFields.length > 0) {
    throw new Error(`Missing required fields: ${missingFields.join(', ')}`);
  }

  // Validate date format (YYYY-MM-DD)
  const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
  if (!dateRegex.test(data.tgl_lahir_prj)) {
    throw new Error('Invalid date format for tgl_lahir_prj. Use YYYY-MM-DD');
  }

  return true;
}

/**
 * Create new Praremaja data entry
 * @param data - PrjData without id (auto-generated by Supabase)
 * @returns Promise<PrjData> - Created Praremaja data with id
 */
export async function createPrjData(data: Omit<PrjData, 'id'>): Promise<PrjData> {
  try {
    validatePrjData(data);
    
    const { data: insertedData, error } = await supabase
      .from('data_praremaja')
      .insert([data])
      .select()
      .single();

    if (error) {
      console.error('Error creating Praremaja data:', error);
      throw new Error(`Failed to create Praremaja data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([insertedData]);
    return transformed[0];
  } catch (error) {
    console.error('Error in createPrjData:', error);
    throw error;
  }
}

/**
 * Fetch all Praremaja data entries
 * @returns Promise<PrjData[]> - Array of all Praremaja data
 */
export async function getAllPrjData(): Promise<PrjData[]> {
  try {
    const { data, error } = await supabase
      .from('data_praremaja')
      .select('*')
      .order('nama_prj', { ascending: true });

    if (error) {
      console.error('Error fetching all Praremaja data:', error);
      throw new Error(`Failed to fetch Praremaja data: ${error.message}`);
    }

    if (!data || data.length === 0) {
      console.warn('No Praremaja data found in database');
      return [];
    }

    return transformDatabaseResponse(data);
  } catch (error) {
    console.error('Error in getAllPrjData:', error);
    throw error;
  }
}

/**
 * Fetch Praremaja data by id
 * @param id - Praremaja data id
 * @returns Promise<PrjData | null> - Praremaja data or null if not found
 */
export async function getPrjDataById(id: number): Promise<PrjData | null> {
  try {
    const { data, error } = await supabase
      .from('data_praremaja')
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        console.warn(`No Praremaja data found with id: ${id}`);
        return null;
      }
      console.error('Error fetching Praremaja data by id:', error);
      throw new Error(`Failed to fetch Praremaja data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([data]);
    return transformed[0];
  } catch (error) {
    console.error('Error in getPrjDataById:', error);
    throw error;
  }
}

/**
 * Update existing Praremaja data entry
 * @param id - Praremaja data id to update
 * @param data - Partial PrjData with fields to update
 * @returns Promise<PrjData> - Updated Praremaja data
 */
export async function updatePrjData(id: number, data: Partial<Omit<PrjData, 'id'>>): Promise<PrjData> {
  try {
    if (Object.keys(data).length === 0) {
      throw new Error('No fields provided for update');
    }

    // Validate date if provided
    if (data.tgl_lahir_prj) {
      const dateRegex = /^\d{4}-\d{2}-\d{2}$/;
      if (!dateRegex.test(data.tgl_lahir_prj)) {
        throw new Error('Invalid date format for tgl_lahir_prj. Use YYYY-MM-DD');
      }
    }

    const { data: updatedData, error } = await supabase
      .from('data_praremaja')
      .update(data)
      .eq('id', id)
      .select()
      .single();

    if (error) {
      if (error.code === 'PGRST116') {
        throw new Error(`No Praremaja data found with id: ${id}`);
      }
      console.error('Error updating Praremaja data:', error);
      throw new Error(`Failed to update Praremaja data: ${error.message}`);
    }

    const transformed = transformDatabaseResponse([updatedData]);
    return transformed[0];
  } catch (error) {
    console.error('Error in updatePrjData:', error);
    throw error;
  }
}

/**
 * Delete Praremaja data entry by id
 * @param id - Praremaja data id to delete
 * @returns Promise<boolean> - True if deletion successful
 */
export async function deletePrjData(id: number): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('data_praremaja')
      .delete()
      .eq('id', id);

    if (error) {
      if (error.code === 'PGRST116') {
        throw new Error(`No Praremaja data found with id: ${id}`);
      }
      console.error('Error deleting Praremaja data:', error);
      throw new Error(`Failed to delete Praremaja data: ${error.message}`);
    }

    return true;
  } catch (error) {
    console.error('Error in deletePrjData:', error);
    throw error;
  }
}

/**
 * Filter Praremaja data by specific criteria
 * @param filters - Partial PrjData with filter values
 * @param page - Page number for pagination (default: 1)
 * @param limit - Number of items per page (default: 10)
 * @returns Promise<PrjData[]> - Filtered Praremaja data with pagination
 */
export async function filterPrjData(
  filters: Partial<Omit<PrjData, 'id'>>,
  page: number = 1,
  limit: number = 10
): Promise<PrjData[]> {
  try {
    if (Object.keys(filters).length === 0) {
      throw new Error('No filter criteria provided');
    }

    let query = supabase.from('data_praremaja').select('*');

    // Build filter query
    Object.entries(filters).forEach(([key, value]) => {
      if (value) {
        query = query.ilike(key, `%${value}%`);
      }
    });

    // Add pagination
    const offset = (page - 1) * limit;
    query = query.range(offset, offset + limit - 1).order('nama_prj', { ascending: true });

    const { data, error } = await query;

    if (error) {
      console.error('Error filtering Praremaja data:', error);
      throw new Error(`Failed to filter Praremaja data: ${error.message}`);
    }

    if (!data || data.length === 0) {
      console.warn('No Praremaja data found matching filter criteria');
      return [];
    }

    return transformDatabaseResponse(data);
  } catch (error) {
    console.error('Error in filterPrjData:', error);
    throw error;
  }
}

// Legacy export for backward compatibility (deprecated)
// Use getAllPrjData() instead
export const prjData: PrjData[] = [];